import "../style/global.css";
require("dotenv").config();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Poppins } from "next/font/google";
const poppins = Poppins({
  weight: ["100", "400", "700"],
  style: ["normal", "italic"],
  display: "swap",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const muiEnv =
    process.env.NODE_ENV === "development" ? "development" : "production";

  return (
    <html lang="pt-BR" className={poppins.className}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href={`https://unpkg.com/@mui/material@latest/umd/material-ui.${muiEnv}.js`}
        />
      </head>

      <body className="h-screen w-screen p-2 ligth:bg-background-light dark:bg-background-dark bg-center bg-cover bg-no-repeat">
        {children}
      </body>
    </html>
  );
}
